package org.telegram.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import org.telegram.dao.User;
import org.telegram.dao.Dialog;
import org.telegram.dao.GroupChat;
import org.telegram.dao.SecretChat;
import org.telegram.dao.Message;
import org.telegram.dao.Contact;
import org.telegram.dao.MediaRecord;

import org.telegram.dao.UserDao;
import org.telegram.dao.DialogDao;
import org.telegram.dao.GroupChatDao;
import org.telegram.dao.SecretChatDao;
import org.telegram.dao.MessageDao;
import org.telegram.dao.ContactDao;
import org.telegram.dao.MediaRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig dialogDaoConfig;
    private final DaoConfig groupChatDaoConfig;
    private final DaoConfig secretChatDaoConfig;
    private final DaoConfig messageDaoConfig;
    private final DaoConfig contactDaoConfig;
    private final DaoConfig mediaRecordDaoConfig;

    private final UserDao userDao;
    private final DialogDao dialogDao;
    private final GroupChatDao groupChatDao;
    private final SecretChatDao secretChatDao;
    private final MessageDao messageDao;
    private final ContactDao contactDao;
    private final MediaRecordDao mediaRecordDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        dialogDaoConfig = daoConfigMap.get(DialogDao.class).clone();
        dialogDaoConfig.initIdentityScope(type);

        groupChatDaoConfig = daoConfigMap.get(GroupChatDao.class).clone();
        groupChatDaoConfig.initIdentityScope(type);

        secretChatDaoConfig = daoConfigMap.get(SecretChatDao.class).clone();
        secretChatDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        contactDaoConfig = daoConfigMap.get(ContactDao.class).clone();
        contactDaoConfig.initIdentityScope(type);

        mediaRecordDaoConfig = daoConfigMap.get(MediaRecordDao.class).clone();
        mediaRecordDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        dialogDao = new DialogDao(dialogDaoConfig, this);
        groupChatDao = new GroupChatDao(groupChatDaoConfig, this);
        secretChatDao = new SecretChatDao(secretChatDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);
        contactDao = new ContactDao(contactDaoConfig, this);
        mediaRecordDao = new MediaRecordDao(mediaRecordDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Dialog.class, dialogDao);
        registerDao(GroupChat.class, groupChatDao);
        registerDao(SecretChat.class, secretChatDao);
        registerDao(Message.class, messageDao);
        registerDao(Contact.class, contactDao);
        registerDao(MediaRecord.class, mediaRecordDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        dialogDaoConfig.getIdentityScope().clear();
        groupChatDaoConfig.getIdentityScope().clear();
        secretChatDaoConfig.getIdentityScope().clear();
        messageDaoConfig.getIdentityScope().clear();
        contactDaoConfig.getIdentityScope().clear();
        mediaRecordDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public DialogDao getDialogDao() {
        return dialogDao;
    }

    public GroupChatDao getGroupChatDao() {
        return groupChatDao;
    }

    public SecretChatDao getSecretChatDao() {
        return secretChatDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public ContactDao getContactDao() {
        return contactDao;
    }

    public MediaRecordDao getMediaRecordDao() {
        return mediaRecordDao;
    }

}
