package org.telegram.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FULL_GROUP.
 */
public class FullGroup {

    private long id;
    /** Not-null value. */
    private byte[] users;

    public FullGroup() {
    }

    public FullGroup(long id) {
        this.id = id;
    }

    public FullGroup(long id, byte[] users) {
        this.id = id;
        this.users = users;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    /** Not-null value. */
    public byte[] getUsers() {
        return users;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUsers(byte[] users) {
        this.users = users;
    }

}
