package org.telegram.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import org.telegram.dao.FullGroup;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table FULL_GROUP.
*/
public class FullGroupDao extends AbstractDao<FullGroup, Long> {

    public static final String TABLENAME = "FULL_GROUP";

    /**
     * Properties of entity FullGroup.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Users = new Property(1, byte[].class, "users", false, "USERS");
    };


    public FullGroupDao(DaoConfig config) {
        super(config);
    }
    
    public FullGroupDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'FULL_GROUP' (" + //
                "'_id' INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "'USERS' BLOB NOT NULL );"); // 1: users
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'FULL_GROUP'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FullGroup entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindBlob(2, entity.getUsers());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public FullGroup readEntity(Cursor cursor, int offset) {
        FullGroup entity = new FullGroup( //
            cursor.getLong(offset + 0), // id
            cursor.getBlob(offset + 1) // users
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FullGroup entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setUsers(cursor.getBlob(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(FullGroup entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(FullGroup entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
