package org.telegram.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GROUP.
 */
public class Group {

    private long id;
    /** Not-null value. */
    private String title;
    private Boolean isForbidden;
    private byte[] avatar;
    private Boolean isLeftGroup;
    private Integer usersCount;
    private byte[] users;

    public Group() {
    }

    public Group(long id) {
        this.id = id;
    }

    public Group(long id, String title, Boolean isForbidden, byte[] avatar, Boolean isLeftGroup, Integer usersCount, byte[] users) {
        this.id = id;
        this.title = title;
        this.isForbidden = isForbidden;
        this.avatar = avatar;
        this.isLeftGroup = isLeftGroup;
        this.usersCount = usersCount;
        this.users = users;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    public Boolean getIsForbidden() {
        return isForbidden;
    }

    public void setIsForbidden(Boolean isForbidden) {
        this.isForbidden = isForbidden;
    }

    public byte[] getAvatar() {
        return avatar;
    }

    public void setAvatar(byte[] avatar) {
        this.avatar = avatar;
    }

    public Boolean getIsLeftGroup() {
        return isLeftGroup;
    }

    public void setIsLeftGroup(Boolean isLeftGroup) {
        this.isLeftGroup = isLeftGroup;
    }

    public Integer getUsersCount() {
        return usersCount;
    }

    public void setUsersCount(Integer usersCount) {
        this.usersCount = usersCount;
    }

    public byte[] getUsers() {
        return users;
    }

    public void setUsers(byte[] users) {
        this.users = users;
    }

}
