package org.telegram.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SECRET_CHAT.
 */
public class SecretChat {

    private long id;
    private long accessHash;
    private int uid;
    private int state;
    private boolean isOut;
    private byte[] key;
    private Integer selfDestruct;

    public SecretChat() {
    }

    public SecretChat(long id) {
        this.id = id;
    }

    public SecretChat(long id, long accessHash, int uid, int state, boolean isOut, byte[] key, Integer selfDestruct) {
        this.id = id;
        this.accessHash = accessHash;
        this.uid = uid;
        this.state = state;
        this.isOut = isOut;
        this.key = key;
        this.selfDestruct = selfDestruct;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getAccessHash() {
        return accessHash;
    }

    public void setAccessHash(long accessHash) {
        this.accessHash = accessHash;
    }

    public int getUid() {
        return uid;
    }

    public void setUid(int uid) {
        this.uid = uid;
    }

    public int getState() {
        return state;
    }

    public void setState(int state) {
        this.state = state;
    }

    public boolean getIsOut() {
        return isOut;
    }

    public void setIsOut(boolean isOut) {
        this.isOut = isOut;
    }

    public byte[] getKey() {
        return key;
    }

    public void setKey(byte[] key) {
        this.key = key;
    }

    public Integer getSelfDestruct() {
        return selfDestruct;
    }

    public void setSelfDestruct(Integer selfDestruct) {
        this.selfDestruct = selfDestruct;
    }

}
