package org.telegram.android.countries;

/**
 * Author: Korshakov Stepan
 * Created: 31.07.13 6:05
 */
public class Countries {

    public static final CountryRecord DEFAULT = new CountryRecord("United States", "us", 1);

    public static final CountryRecord[] COUNTRIES = new CountryRecord[]
            {
                    new CountryRecord("Afghanistan", "af", 93),
                    new CountryRecord("Albania", "al", 355),
                    new CountryRecord("Algeria", "dz", 213),
                    new CountryRecord("American Samoa", "as", 1684),
                    new CountryRecord("Andorra", "ad", 376),
                    new CountryRecord("Angola", "ao", 244),
                    new CountryRecord("Anguilla", "ai", 1264),
                    new CountryRecord("Antarctica", "aq", 672),
                    new CountryRecord("Antigua and Barbuda", "ag", 1268),
                    new CountryRecord("Argentina", "ar", 54),
                    new CountryRecord("Armenia", "am", 374),
                    new CountryRecord("Aruba", "aw", 297),
                    new CountryRecord("Australia", "au", 61),
                    new CountryRecord("Austria", "at", 43),
                    new CountryRecord("Azerbaijan", "az", 994),
                    new CountryRecord("Bahamas", "bs", 1242),
                    new CountryRecord("Bahrain", "bh", 973),
                    new CountryRecord("Bangladesh", "bd", 880),
                    new CountryRecord("Barbados", "bb", 1246),
                    new CountryRecord("Belarus", "by", 375),
                    new CountryRecord("Belgium", "be", 32),
                    new CountryRecord("Belize", "bz", 501),
                    new CountryRecord("Benin", "bj", 229),
                    new CountryRecord("Bermuda", "bm", 1441),
                    new CountryRecord("Bhutan", "bt", 975),
                    new CountryRecord("Bolivia", "bo", 591),
                    new CountryRecord("Bosnia and Herzegovina", "ba", 387),
                    new CountryRecord("Botswana", "bw", 267),
                    new CountryRecord("Brazil", "br", 55),
                    new CountryRecord("British Virgin Islands", "vg", 1284),
                    new CountryRecord("Brunei", "bn", 673),
                    new CountryRecord("Bulgaria", "bg", 359),
                    new CountryRecord("Burkina Faso", "bf", 226),
                    new CountryRecord("Burma (Myanmar)", "mm", 95),
                    new CountryRecord("Burundi", "bi", 257),
                    new CountryRecord("Cambodia", "kh", 855),
                    new CountryRecord("Cameroon", "cm", 237),
                    new CountryRecord("Canada", "ca", 1, true),
                    new CountryRecord("Cape Verde", "cv", 238),
                    new CountryRecord("Cayman Islands", "ky", 1345),
                    new CountryRecord("Central African Republic", "cf", 236),
                    new CountryRecord("Chad", "td", 235),
                    new CountryRecord("Chile", "cl", 56),
                    new CountryRecord("China", "cn", 86),
                    new CountryRecord("Christmas Island", "cx", 61),
                    new CountryRecord("Cocos (Keeling) Islands", "cc", 61),
                    new CountryRecord("Colombia", "co", 57),
                    new CountryRecord("Comoros", "km", 269),
                    new CountryRecord("Republic of the Congo", "cg", 242),
                    new CountryRecord("Democratic Republic of the Congo", "cd", 243),
                    new CountryRecord("Cook Islands", "ck", 682),
                    new CountryRecord("Costa Rica", "cr", 506),
                    new CountryRecord("Croatia", "hr", 385),
                    new CountryRecord("Cuba", "cu", 53),
                    new CountryRecord("Cyprus", "cy", 357),
                    new CountryRecord("Czech Republic", "cz", 420),
                    new CountryRecord("Denmark", "dk", 45),
                    new CountryRecord("Djibouti", "dj", 253),
                    new CountryRecord("Dominica", "dm", 1767),
                    new CountryRecord("Dominican Republic", "do", 1809),
                    new CountryRecord("Timor-Leste", "tl", 670),
                    new CountryRecord("Ecuador", "ec", 593),
                    new CountryRecord("Egypt", "eg", 20),
                    new CountryRecord("El Salvador", "sv", 503),
                    new CountryRecord("Equatorial Guinea", "gq", 240),
                    new CountryRecord("Eritrea", "er", 291),
                    new CountryRecord("Estonia", "ee", 372),
                    new CountryRecord("Ethiopia", "et", 251),
                    new CountryRecord("Falkland Islands", "fk", 500),
                    new CountryRecord("Faroe Islands", "fo", 298),
                    new CountryRecord("Fiji", "fj", 679),
                    new CountryRecord("Finland", "fi", 358),
                    new CountryRecord("France", "fr", 33),
                    new CountryRecord("French Polynesia", "pf", 689),
                    new CountryRecord("Gabon", "ga", 241),
                    new CountryRecord("Gambia", "gm", 220),
                    new CountryRecord("Georgia", "ge", 995),
                    new CountryRecord("Germany", "de", 49),
                    new CountryRecord("Ghana", "gh", 233),
                    new CountryRecord("Gibraltar", "gi", 350),
                    new CountryRecord("Greece", "gr", 30),
                    new CountryRecord("Greenland", "gl", 299),
                    new CountryRecord("Grenada", "gd", 1473),
                    new CountryRecord("Guam", "gu", 1671),
                    new CountryRecord("Guatemala", "gt", 502),
                    new CountryRecord("Guinea", "gn", 224),
                    new CountryRecord("Guinea-Bissau", "gw", 245),
                    new CountryRecord("Guyana", "gy", 592),
                    new CountryRecord("Haiti", "ht", 509),
                    new CountryRecord("Honduras", "hn", 504),
                    new CountryRecord("Hong Kong", "hk", 852),
                    new CountryRecord("Hungary", "hu", 36),
                    new CountryRecord("Iceland", "is", 354),
                    new CountryRecord("India", "in", 91),
                    new CountryRecord("Indonesia", "id", 62),
                    new CountryRecord("Iran", "ir", 98),
                    new CountryRecord("Iraq", "iq", 964),
                    new CountryRecord("Ireland", "ie", 353),
                    new CountryRecord("Isle of Man", "im", 44, true),
                    new CountryRecord("Israel", "il", 972),
                    new CountryRecord("Italy", "it", 39),
                    new CountryRecord("Ivory Coast", "ci", 225),
                    new CountryRecord("Jamaica", "jm", 1876),
                    new CountryRecord("Japan", "jp", 81),
                    new CountryRecord("Jordan", "jo", 962),
                    new CountryRecord("Kazakhstan", "kz", 7, true),
                    new CountryRecord("Kenya", "ke", 254),
                    new CountryRecord("Kiribati", "ki", 686),
                    new CountryRecord("Kuwait", "kw", 965),
                    new CountryRecord("Kyrgyzstan", "kg", 996),
                    new CountryRecord("Laos", "la", 856),
                    new CountryRecord("Latvia", "lv", 371),
                    new CountryRecord("Lebanon", "lb", 961),
                    new CountryRecord("Lesotho", "ls", 266),
                    new CountryRecord("Liberia", "lr", 231),
                    new CountryRecord("Libya", "ly", 218),
                    new CountryRecord("Liechtenstein", "li", 423),
                    new CountryRecord("Lithuania", "lt", 370),
                    new CountryRecord("Luxembourg", "lu", 352),
                    new CountryRecord("Macau", "mo", 853),
                    new CountryRecord("Macedonia", "mk", 389),
                    new CountryRecord("Madagascar", "mg", 261),
                    new CountryRecord("Malawi", "mw", 265),
                    new CountryRecord("Malaysia", "my", 60),
                    new CountryRecord("Maldives", "mv", 960),
                    new CountryRecord("Mali", "ml", 223),
                    new CountryRecord("Malta", "mt", 356),
                    new CountryRecord("Marshall Islands", "mh", 692),
                    new CountryRecord("Mauritania", "mr", 222),
                    new CountryRecord("Mauritius", "mu", 230),
                    new CountryRecord("Mayotte", "yt", 262),
                    new CountryRecord("Mexico", "mx", 52),
                    new CountryRecord("Micronesia", "fm", 691),
                    new CountryRecord("Moldova", "md", 373),
                    new CountryRecord("Monaco", "mc", 377),
                    new CountryRecord("Mongolia", "mn", 976),
                    new CountryRecord("Montenegro", "me", 382),
                    new CountryRecord("Montserrat", "ms", 1664),
                    new CountryRecord("Morocco", "ma", 212),
                    new CountryRecord("Mozambique", "mz", 258),
                    new CountryRecord("Namibia", "na", 264),
                    new CountryRecord("Nauru", "nr", 674),
                    new CountryRecord("Nepal", "np", 977),
                    new CountryRecord("Netherlands", "nl", 31),
                    new CountryRecord("Netherlands Antilles", "an", 599),
                    new CountryRecord("New Caledonia", "nc", 687),
                    new CountryRecord("New Zealand", "nz", 64),
                    new CountryRecord("Nicaragua", "ni", 505),
                    new CountryRecord("Niger", "ne", 227),
                    new CountryRecord("Nigeria", "ng", 234),
                    new CountryRecord("Niue", "nu", 683),
                    new CountryRecord("Northern Mariana Islands", "mp", 1670),
                    new CountryRecord("North Korea", "kp", 850),
                    new CountryRecord("Norway", "no", 47),
                    new CountryRecord("Oman", "om", 968),
                    new CountryRecord("Pakistan", "pk", 92),
                    new CountryRecord("Palau", "pw", 680),
                    new CountryRecord("Panama", "pa", 507),
                    new CountryRecord("Papua New Guinea", "pg", 675),
                    new CountryRecord("Paraguay", "py", 595),
                    new CountryRecord("Peru", "pe", 51),
                    new CountryRecord("Philippines", "ph", 63),
                    new CountryRecord("Pitcairn Islands", "pn", 870),
                    new CountryRecord("Poland", "pl", 48),
                    new CountryRecord("Portugal", "pt", 351),
                    new CountryRecord("Puerto Rico", "pr", 1, true),
                    new CountryRecord("Qatar", "qa", 974),
                    new CountryRecord("Romania", "ro", 40),
                    new CountryRecord("Russia", "ru", 7),
                    new CountryRecord("Rwanda", "rw", 250),
                    new CountryRecord("Saint Barthelemy", "bl", 590),
                    new CountryRecord("Samoa", "ws", 685),
                    new CountryRecord("San Marino", "sm", 378),
                    new CountryRecord("Sao Tome and Principe", "st", 239),
                    new CountryRecord("Saudi Arabia", "sa", 966),
                    new CountryRecord("Senegal", "sn", 221),
                    new CountryRecord("Serbia", "rs", 381),
                    new CountryRecord("Seychelles", "sc", 248),
                    new CountryRecord("Sierra Leone", "sl", 232),
                    new CountryRecord("Singapore", "sg", 65),
                    new CountryRecord("Slovakia", "sk", 421),
                    new CountryRecord("Slovenia", "si", 386),
                    new CountryRecord("Solomon Islands", "sb", 677),
                    new CountryRecord("Somalia", "so", 252),
                    new CountryRecord("South Africa", "za", 27),
                    new CountryRecord("South Korea", "kr", 82),
                    new CountryRecord("Spain", "es", 34),
                    new CountryRecord("Sri Lanka", "lk", 94),
                    new CountryRecord("Saint Helena", "sh", 290),
                    new CountryRecord("Saint Kitts and Nevis", "kn", 1869),
                    new CountryRecord("Saint Lucia", "lc", 1758),
                    new CountryRecord("Saint Martin", "mf", 1599),
                    new CountryRecord("Saint Pierre and Miquelon", "pm", 508),
                    new CountryRecord("Saint Vincent and the Grenadines", "vc", 1784),
                    new CountryRecord("Sudan", "sd", 249),
                    new CountryRecord("Suriname", "sr", 597),
                    new CountryRecord("Swaziland", "sz", 268),
                    new CountryRecord("Sweden", "se", 46),
                    new CountryRecord("Switzerland", "ch", 41),
                    new CountryRecord("Syria", "sy", 963),
                    new CountryRecord("Taiwan", "tw", 886),
                    new CountryRecord("Tajikistan", "tj", 992),
                    new CountryRecord("Tanzania", "tz", 255),
                    new CountryRecord("Thailand", "th", 66),
                    new CountryRecord("Togo", "tg", 228),
                    new CountryRecord("Tokelau", "tk", 690),
                    new CountryRecord("Tonga", "to", 676),
                    new CountryRecord("Trinidad and Tobago", "tt", 1868),
                    new CountryRecord("Tunisia", "tn", 216),
                    new CountryRecord("Turkey", "tr", 90),
                    new CountryRecord("Turkmenistan", "tm", 993),
                    new CountryRecord("Turks and Caicos Islands", "tc", 1649),
                    new CountryRecord("Tuvalu", "tv", 688),
                    new CountryRecord("United Arab Emirates", "ae", 971),
                    new CountryRecord("Uganda", "ug", 256),
                    new CountryRecord("United Kingdom", "gb", 44),
                    new CountryRecord("Ukraine", "ua", 380),
                    new CountryRecord("Uruguay", "uy", 598),
                    new CountryRecord("United States", "us", 1),
                    new CountryRecord("Uzbekistan", "uz", 998),
                    new CountryRecord("Vanuatu", "vu", 678),
                    new CountryRecord("Holy See (Vatican City)", "va", 39),
                    new CountryRecord("Venezuela", "ve", 58),
                    new CountryRecord("Vietnam", "vn", 84),
                    new CountryRecord("US Virgin Islands", "vi", 1340),
                    new CountryRecord("Wallis and Futuna", "wf", 681),
                    new CountryRecord("Yemen", "ye", 967),
                    new CountryRecord("Zambia", "zm", 260),
                    new CountryRecord("Zimbabwe", "zw", 263),
                    new CountryRecord("Select country", "??", -1),
            };
}
